# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YuanXC' do
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MBProgressHUD’, '~> 0.9'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'JSONModel'
  pod 'TZImagePickerController', '2.2.5'
  pod 'WebViewJavascriptBridge', '~> 6.0'

pod 'IQKeyboardManager'

pod 'BRPickerView', '~> 2.2.1'
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
  pod 'UMCAnalytics'

end
